#!/usr/bin/env python3
"""Generate the bounded x86-64 syscall-number contract."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
import re
import tempfile


HERE = Path(__file__).resolve().parent
KERNEL_ROOT = HERE.parents[1]
SOURCE = KERNEL_ROOT / "src/arch/x86/user_syscalls.json"
OUTPUT = KERNEL_ROOT / "src/arch/x86/user_syscalls_generated.h"
CONSTANT_RE = re.compile(r"U64_SYS_[A-Z0-9_]+\Z")
NAME_RE = re.compile(r"[a-z][a-z0-9-]*\Z")


def digest_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def load() -> dict:
    return json.loads(SOURCE.read_text())


def validate(value: dict) -> None:
    if value.get("schema") != "zlos.user-syscalls.v1" \
            or value.get("abi_version") != 1 \
            or value.get("architecture") != "x86_64" \
            or value.get("mechanism") != "int 0x80" \
            or value.get("unknown_result") != "ENOSYS":
        raise ValueError("wrong syscall contract schema or ABI policy")
    entries = value.get("entries", [])
    if not isinstance(entries, list) or not entries:
        raise ValueError("syscall contract has no entries")
    numbers = [row.get("number") for row in entries]
    constants = [row.get("constant") for row in entries]
    names = [row.get("name") for row in entries]
    if any(not isinstance(number, int) or isinstance(number, bool)
           or number <= 0 or number >= 1 << 63 for number in numbers):
        raise ValueError("syscall number is not a positive non-sign-bit integer")
    if len(set(numbers)) != len(numbers) or numbers != sorted(numbers):
        raise ValueError("syscall numbers are duplicate or unordered")
    if numbers != list(range(numbers[0], numbers[-1] + 1)):
        raise ValueError("current ABI syscall range has an undeclared gap")
    if numbers[0] != 1:
        raise ValueError("syscall zero must remain outside the admitted ABI")
    if len(set(constants)) != len(constants) \
            or any(not isinstance(item, str) or not CONSTANT_RE.fullmatch(item)
                   for item in constants):
        raise ValueError("syscall constant is duplicate or malformed")
    if len(set(names)) != len(names) \
            or any(not isinstance(item, str) or not NAME_RE.fullmatch(item)
                   for item in names):
        raise ValueError("syscall name is duplicate or malformed")


def render(value: dict) -> str:
    validate(value)
    entries = value["entries"]
    source_sha = digest_bytes(SOURCE.read_bytes())
    lines = [
        "/* Generated by kernel/tools/generators/gen-user-syscalls.py. */",
        "/* Source SHA-256: " + source_sha + " */",
        "#ifndef ZLOS_USER_SYSCALLS_GENERATED_H",
        "#define ZLOS_USER_SYSCALLS_GENERATED_H",
        "",
        f"#define ZLOS_U64_SYSCALL_ABI_VERSION {value['abi_version']}ULL",
        f"#define ZLOS_U64_SYSCALL_FIRST {entries[0]['number']}ULL",
        f"#define ZLOS_U64_SYSCALL_LAST {entries[-1]['number']}ULL",
    ]
    lines.extend(
        f"#define {row['constant']} {row['number']}ULL" for row in entries
    )
    lines.extend([
        "",
        "static int zlos_u64_syscall_known(unsigned long long number)",
        "{",
        "    switch (number) {",
    ])
    lines.extend(f"    case {row['constant']}:" for row in entries)
    lines.extend([
        "        return 1;",
        "    default:",
        "        return 0;",
        "    }",
        "}",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def selftest(value: dict) -> None:
    mutations = {}
    duplicate = copy.deepcopy(value)
    duplicate["entries"][1]["number"] = duplicate["entries"][0]["number"]
    mutations["duplicate-number"] = duplicate
    gap = copy.deepcopy(value)
    gap["entries"].pop(10)
    mutations["undeclared-gap"] = gap
    sign = copy.deepcopy(value)
    sign["entries"][-1]["number"] = 1 << 63
    mutations["sign-bit-number"] = sign
    zero = copy.deepcopy(value)
    zero["entries"][0]["number"] = 0
    mutations["syscall-zero"] = zero
    constant = copy.deepcopy(value)
    constant["entries"][0]["constant"] = "unsafe constant"
    mutations["malformed-constant"] = constant
    version = copy.deepcopy(value)
    version["abi_version"] = 2
    mutations["unadmitted-version"] = version
    caught = []
    for name, mutant in mutations.items():
        try:
            validate(mutant)
        except (ValueError, TypeError):
            caught.append(name)
        else:
            raise ValueError(f"syscall generator mutation escaped: {name}")
    print("user-syscalls selftest: caught " + ", ".join(caught))


def write_atomic(value: str) -> None:
    with tempfile.NamedTemporaryFile("w", dir=OUTPUT.parent, delete=False,
                                     encoding="utf-8") as handle:
        handle.write(value)
        temporary = Path(handle.name)
    os.replace(temporary, OUTPUT)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("choose exactly one of --write or --check")
    try:
        value = load()
        generated = render(value)
        if args.selftest:
            selftest(value)
        if args.write:
            write_atomic(generated)
        elif not OUTPUT.is_file() or OUTPUT.read_text() != generated:
            raise ValueError("generated syscall header is stale; run --write and inspect")
        print(
            f"user-syscalls: PASS: ABI {value['abi_version']}, "
            f"{len(value['entries'])} entries, unsigned unknown IDs -> ENOSYS"
        )
        return 0
    except (OSError, ValueError, TypeError, json.JSONDecodeError) as error:
        print(f"user-syscalls: FAIL: {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
