#!/usr/bin/env python3
"""gen_gpu_surface.py - lift Gen9's RENDER_SURFACE_STATE layout out of Mesa.

WHY THIS EXISTS. This was the last thing blocking the render engine, and it
looked unobtainable: no genxml on disk, no ISL headers, no Intel files in
libdrm-dev, and twelve INTEL_DEBUG flags that print field NAMES but never a
surface state's bit positions.

The layout was on this machine the whole time. Mesa's decoder is compiled into
libgallium, and it carries its genxml database ZLIB-COMPRESSED. Scanning the 46 MB
driver for zlib streams and decompressing each until one contains
"RENDER_SURFACE_STATE" yields 1.86 MB of XML covering gens 4 through 35 - the
authoritative bit positions, from the vendor's own driver, on the exact machine
the driver targets.

The earlier attempt failed because it scanned `iris_dri.so`, which is a 121 KB
SYMLINK TO THE LOADER. The real driver is libgallium-<version>.so.

    ./tools/generators/gen_gpu_surface.py > src/drivers/display/assets/gpu_surface.inc
"""
import glob, re, sys, zlib

def find_genxml():
    for so in sorted(glob.glob('/usr/lib/*/libgallium*.so')) + \
              sorted(glob.glob('/usr/lib/*/dri/*_dri.so')):
        try:
            d = open(so, 'rb').read()
        except OSError:
            continue
        if len(d) < 1_000_000:        # the loader stub, not the driver
            continue
        i = 0
        while True:
            i = d.find(b'\x78', i)
            if i < 0 or i >= len(d) - 2:
                break
            if d[i+1] in (0x01, 0x5e, 0x9c, 0xda):
                try:
                    out = zlib.decompressobj().decompress(d[i:i+4_000_000], 8_000_000)
                    if b'RENDER_SURFACE_STATE' in out:
                        return so, out.decode('utf-8', 'replace')
                except Exception:
                    pass
            i += 1
    return None, None

def main():
    so, xml = find_genxml()
    if not xml:
        sys.exit("no genxml found - is Mesa installed? (looked in libgallium and dri/)")

    # split per generation; take gen 9
    starts = [(m.start(), m.group(1)) for m in
              re.finditer(r'<genxml name="[^"]*" gen="([0-9]+)"', xml)]
    sec = None
    for i, (off, g) in enumerate(starts):
        if g == "9":
            end = starts[i+1][0] if i + 1 < len(starts) else len(xml)
            sec = xml[off:end]
            break
    if sec is None:
        sys.exit("genxml has no gen=9 section")
    m = re.search(r'<struct name="RENDER_SURFACE_STATE"[^>]*>(.*?)</struct>', sec, re.S)
    if not m:
        sys.exit("gen9 section has no RENDER_SURFACE_STATE")
    rss = m.group(0)

    fields = [(n, int(dw), int(hi), int(lo))
              for n, dw, hi, lo in
              re.findall(r'<field name="([^"]+)" dword="(\d+)" bits="(\d+):(\d+)"', rss)]
    length = int(re.search(r'length="(\d+)"', rss).group(1))

    # only what a render target actually sets - the rest stay zero
    NEED = ("Surface Type", "Surface Format", "Tile Mode",
            "Surface Horizontal Alignment", "Surface Vertical Alignment",
            "Width", "Height", "Surface Pitch", "Depth",
            "Render Target View Extent", "Surface Base Address")

    def c_name(n):
        return "GPU_RSS_" + re.sub(r'[^A-Z0-9]+', '_', n.upper()).strip('_')

    print("/* gpu_surface.inc - GENERATED by gen_gpu_surface.py. Do not edit by hand.")
    print(" *")
    print(" * Gen9 RENDER_SURFACE_STATE field positions, lifted out of Mesa's own")
    print(" * decoder database - which ships ZLIB-COMPRESSED inside libgallium, which is")
    print(" * why twelve INTEL_DEBUG flags and four filesystem searches never found it.")
    print(f" * Source: {so}")
    print(" *")
    print(f" * The structure is {length} dwords. Only the fields a render target sets are")
    print(" * emitted; everything else is zero, which is the correct default for a")
    print(" * linear 2D colour target with no auxiliary surface.")
    print(" *")
    print(" * Each field is a dword index, a shift and a mask, so a builder writes")
    print(" *     dw[GPU_RSS_WIDTH_DW] |= (v & GPU_RSS_WIDTH_MASK) << GPU_RSS_WIDTH_SHIFT;")
    print(" * and cannot silently put a value in the wrong dword.")
    print(" */")
    print(f"#define GPU_RSS_DWORDS {length}u")
    print()
    for n, dw, hi, lo in fields:
        if not any(w.lower() == n.lower() for w in NEED):
            continue
        base = c_name(n)
        width = hi - lo + 1
        # 64-bit address fields span two dwords; emit the low dword and note it
        if width > 32:
            print(f"/* {n}: {width} bits from dw{dw} - spans two dwords, write low then high */")
            print(f"#define {base}_DW    {dw}u")
            print(f"#define {base}_SHIFT {lo}u")
            print(f"#define {base}_IS64  1")
        else:
            mask = (1 << width) - 1
            print(f"/* {n}  dw{dw} bits {hi}:{lo} */")
            print(f"#define {base}_DW    {dw}u")
            print(f"#define {base}_SHIFT {lo}u")
            print(f"#define {base}_MASK  0x{mask:X}u")
        print()

    # the enums a colour target needs
    print("/* the enum values a linear 2D colour target uses */")
    for pat in (r'<value name="(SURFTYPE_2D)" value="(\d+)"',
                r'<value name="(LINEAR)" value="(\d+)"',
                r'<value name="(XMAJOR)" value="(\d+)"',
                r'<value name="(YMAJOR)" value="(\d+)"'):
        mm = re.search(pat, rss)
        if mm:
            print(f"#define GPU_RSS_{mm.group(1)} {mm.group(2)}u")

main()
