#!/usr/bin/env python3
# gen_bigfont.py - render a REAL big font into one extra coverage atlas.
#
# Same idea as gen_hd_font.py (which produces font_aa.c), but this emits a
# single, larger cell for huge on-screen text - headlines, hero labels, the
# clock. DejaVu Sans Mono is rendered with FreeType's grayscale hinting straight
# into the exact same style of coverage array the kernel already blends, so it
# is a drop-in for a new fb_text_huge() renderer - no other changes needed.
#
#   font24x48_aa[95][48][24] - huge text, ASCII 32..126, coverage 0..255
#
# Rendering approach mirrors gen_hd_font.py exactly: best_size() picks the
# largest size that fits the cell, the line box is centred vertically, and each
# glyph is drawn with anchor='ls' (left end of the baseline) for terminal-style
# alignment.

import os
from PIL import Image, ImageDraw, ImageFont

KERNEL_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(KERNEL_ROOT, "src", "graphics", "fonts", "font_big.c")
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FIRST, LAST = 32, 126

CELL_W = 24
CELL_H = 48


def best_size(cell_w, cell_h):
    """largest font size whose advance fits cell_w and line fits cell_h"""
    best = 6
    for s in range(6, cell_h * 3):
        f = ImageFont.truetype(FONT, s)
        adv = f.getlength("M")
        asc, desc = f.getmetrics()
        if adv <= cell_w and (asc + desc) <= cell_h + 2:
            best = s
    return best


def render_cell(font, ch, W, H, baseline):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    adv = font.getlength(ch)
    x = (W - adv) / 2.0
    # 'ls' = anchor at the left end of the baseline: proper terminal alignment
    d.text((x, baseline), ch, font=font, fill=255, anchor="ls")
    return [[img.getpixel((x, y)) for x in range(W)] for y in range(H)]


def build(W, H):
    size = best_size(W, H)
    font = ImageFont.truetype(FONT, size)
    asc, desc = font.getmetrics()
    baseline = (H + asc - desc) // 2          # centre the line box vertically
    glyphs = []
    for code in range(FIRST, LAST + 1):
        glyphs.append(render_cell(font, chr(code), W, H, baseline))
    return glyphs, size


def emit(f, name, W, H, glyphs):
    f.write(f"const unsigned char {name}[95][{H}][{W}] = {{\n")
    for i, g in enumerate(glyphs):
        f.write("  { /* %d */\n" % (FIRST + i))
        for row in g:
            f.write("    {" + ",".join("%3d" % v for v in row) + "},\n")
        f.write("  },\n")
    f.write("};\n")


def main():
    huge, h_sz = build(CELL_W, CELL_H)
    with open(OUT, "w") as f:
        f.write("/* font_big.c - GENERATED by gen_bigfont.py. Do not edit by hand.\n")
        f.write(" * Real DejaVu Sans Mono, rendered with FreeType grayscale AA into one\n")
        f.write(f" * extra {CELL_W}x{CELL_H} coverage atlas for huge on-screen text (headlines,\n")
        f.write(f" * hero labels, the clock), rendered at {h_sz}px. fb.c blends fg over the\n")
        f.write(" * background by these coverage values - see fb_text_huge(). */\n")
        emit(f, "font24x48_aa", CELL_W, CELL_H, huge)
    print(f"wrote {OUT}: DejaVu Sans Mono, huge {h_sz}px ({CELL_W}x{CELL_H})")


if __name__ == "__main__":
    main()
