#!/usr/bin/env python3
"""gen_gpu_batch.py - capture Mesa's Gen9 3D command stream, with the dwords.

The batch decoder prints BOTH the decoded field names AND the raw dword values.
That makes the capture a replayable command stream rather than just a reading
aid: zlOS can emit these literal dwords with its own addresses substituted,
instead of deriving 77 packet encodings from a PRM this tree does not have.

    ./tools/generators/gen_gpu_batch.py > src/drivers/display/assets/gpu_batch.inc

WHAT THIS DOES NOT GIVE YOU, and it matters - see gen9-blend-pipeline.md:
RENDER_SURFACE_STATE and BINDING_TABLE_STATE do NOT appear in the dump. The
batch only points at them. zlOS has to build both itself, and the render target
surface state is the one that describes the destination - format, pitch, base
address, tiling. Everything else the draw references (BLEND_STATE,
COLOR_CALC_STATE, CC_VIEWPORT, SF_CLIP_VIEWPORT) IS decoded and is here.
"""
import re, subprocess, sys, os

def capture():
    env = dict(os.environ, MESA_SHADER_CACHE_DISABLE="true", INTEL_DEBUG="bat")
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    exe = os.path.join(root, "tests", "host", "gpu_fillrate")
    if not os.path.exists(exe):
        sys.exit("build kernel/tests/host/gpu_fillrate first (./build.sh there)")
    return subprocess.run([exe], env=env, capture_output=True, text=True).stderr

HDR = re.compile(r'^0x[0-9a-f]+:\s+0x([0-9a-f]{8}):\s+([A-Z0-9_]+)\s*$')
DW  = re.compile(r'^0x[0-9a-f]+:\s+0x([0-9a-f]{8})\s*:\s*Dword\s+(\d+)\s*$')

def main():
    txt = capture()
    if "PIPELINE_SELECT" not in txt:
        sys.exit("no batch in the dump - is INTEL_DEBUG=bat supported by this Mesa?")
    lines = txt.splitlines()
    start = next(i for i, l in enumerate(lines)
                 if (m := HDR.match(l.strip())) and m.group(2) == "PIPELINE_SELECT")
    packets, cur, done = [], None, False
    for l in lines[start:]:
        t = l.strip()
        if (m := HDR.match(t)):
            if done: break
            cur = {"name": m.group(2), "dw": []}
            packets.append(cur)
            if m.group(2) == "3DPRIMITIVE": done = True
        elif (d := DW.match(t)) and cur is not None:
            cur["dw"].append(int(d.group(1), 16))

    total = sum(len(p["dw"]) for p in packets)
    print("/* gpu_batch.inc - GENERATED by gen_gpu_batch.py. Do not edit by hand.")
    print(" *")
    print(" * Mesa's own Gen9 command stream for one alpha-blended quad, captured")
    print(" * from the vendor driver on 8086:9B41 with INTEL_DEBUG=bat. Dword values,")
    print(" * so this can be EMITTED, not just read.")
    print(" *")
    print(" * ADDRESSES IN HERE ARE MESA'S. Every page-aligned dword in GPU-address")
    print(" * range is a patch candidate; zlOS must substitute its own before this")
    print(" * means anything. And RENDER_SURFACE_STATE / BINDING_TABLE_STATE are NOT")
    print(" * captured - the batch only points at them, so zlOS builds those itself.")
    print(" *")
    print(f" * {len(packets)} packets, {total} dwords.")
    print(" */")
    print(f"#define GPU_BATCH_PACKETS {len(packets)}u")
    print(f"#define GPU_BATCH_DWORDS  {total}u")
    print("static const struct { const char *name; unsigned short at, n; } gpu_batch_pkt[] = {")
    off = 0
    for p in packets:
        print(f'    {{ "{p["name"]}", {off}, {len(p["dw"])} }},')
        off += len(p["dw"])
    print("};")
    print("static const unsigned int gpu_batch_dw[GPU_BATCH_DWORDS] = {")
    flat = [x for p in packets for x in p["dw"]]
    for i in range(0, len(flat), 6):
        print("    " + " ".join(f"0x{x:08X}," for x in flat[i:i+6]))
    print("};")

main()
