#!/usr/bin/env python3
"""gen_gpu_shader.py - lift a Gen9 pixel shader out of Mesa, as bytes.

WHY THIS EXISTS. zlOS has no Gen9 assembler, and hand-encoding EU ISA to get a
render-target write right is the kind of job where a wrong bit is a hung GPU
with no diagnostic. It does not have to be hand-encoded: Mesa compiles exactly
the shader we want every time anyone draws a flat colour, and INTEL_DEBUG=fs,hex
prints the machine code.

THE TRAP THAT COST AN HOUR. INTEL_DEBUG=fs looks SILENT on this machine, and it
is easy to conclude the Mesa build has no debug output. It has. The shader CACHE
(~/.cache/mesa_shader_cache, 7.8 MB here) serves a compiled binary and the
compiler never runs, so there is nothing to print. MESA_SHADER_CACHE_DISABLE=true
is the whole difference between 0 lines and 76.

Run it like the other generators here (gen_cursor.py, mkfont.py); the .inc it
writes is COMMITTED, so the kernel builds with no Python and no GL.

    ./tools/generators/gen_gpu_shader.py > src/drivers/display/assets/gpu_shader.inc
"""
import re, struct, subprocess, sys, tempfile, os, textwrap

SRC = r'''
#include <GL/glx.h>
#include <GL/gl.h>
static void*P(const char*n){return (void*)glXGetProcAddressARB((const GLubyte*)n);}
int main(void){
    Display*d=XOpenDisplay(0); if(!d)return 77;
    int att[]={GLX_RGBA,GLX_DOUBLEBUFFER,None};
    XVisualInfo*vi=glXChooseVisual(d,DefaultScreen(d),att); if(!vi)return 77;
    Pixmap pm=XCreatePixmap(d,RootWindow(d,vi->screen),16,16,vi->depth);
    GLXContext cx=glXCreateContext(d,vi,0,True);
    if(!glXMakeCurrent(d,glXCreateGLXPixmap(d,vi,pm),cx))return 77;
    unsigned(*CS)(unsigned)=P("glCreateShader");
    void(*SS)(unsigned,int,const char*const*,const int*)=P("glShaderSource");
    void(*CO)(unsigned)=P("glCompileShader");
    unsigned(*CP)(void)=P("glCreateProgram");
    void(*AT)(unsigned,unsigned)=P("glAttachShader");
    void(*LP)(unsigned)=P("glLinkProgram");
    const char*vs="#version 130\nvoid main(){gl_Position=vec4(0,0,0,1);}\n";
    const char*fs="#version 130\nvoid main(){gl_FragColor=vec4(0.376,0.824,0.922,0.5);}\n";
    unsigned v=CS(0x8B31),f=CS(0x8B30);
    SS(v,1,&vs,0);CO(v); SS(f,1,&fs,0);CO(f);
    unsigned p=CP();AT(p,v);AT(p,f);LP(p);
    return 0;
}
'''

# The four constants the fragment shader writes. Finding them in the byte stream
# is what locates the patch offsets, so they are chosen to be distinctive rather
# than round - 0.5 appears by accident in all sorts of places, 0.376 does not.
WANT = [0.376, 0.824, 0.922, 0.5]

def build_and_dump():
    d = tempfile.mkdtemp()
    c = os.path.join(d, "p.c"); b = os.path.join(d, "p")
    open(c, "w").write(SRC)
    if subprocess.call(["gcc", "-O2", "-w", "-o", b, c, "-lGL", "-lX11"]):
        sys.exit("gcc failed - is libgl1-mesa-dev installed?")
    env = dict(os.environ, MESA_SHADER_CACHE_DISABLE="true", INTEL_DEBUG="fs,hex")
    r = subprocess.run([b], env=env, capture_output=True, text=True)
    return r.stderr

def bytes_of(block):
    out = []
    for line in block.splitlines():
        m = re.match(r'^((?:[0-9a-f]{2} ){16})\S', line.strip())
        if m:
            out += [int(x, 16) for x in m.group(1).split()]
    return out

def main():
    txt = build_and_dump()
    if "SIMD8 shader" not in txt:
        sys.exit("no shader in the dump - MESA_SHADER_CACHE_DISABLE not honoured?")
    blk = txt.split("SIMD8 shader:")[1].split("END B0")[0]
    by = bytes_of(blk)
    if len(by) % 16 or not by:
        sys.exit(f"got {len(by)} bytes, expected a multiple of 16")

    # Locate each constant by VALUE rather than by a fixed offset. An offset
    # table would be right for this Mesa and silently wrong for the next.
    off = []
    for want in WANT:
        w = struct.pack("<f", want)
        i = bytes(by).find(w)
        if i < 0:
            sys.exit(f"constant {want} not found in the shader - cannot locate the patch point")
        off.append(i)

    print("/* gpu_shader.inc - GENERATED by gen_gpu_shader.py. Do not edit by hand.")
    print(" *")
    print(" * A Gen9 SIMD8 fragment shader that writes ONE constant RGBA colour and")
    print(" * ends. Lifted out of Mesa's own compiler with INTEL_DEBUG=fs,hex, because")
    print(" * this tree has no Gen9 assembler and a hand-encoded render-target write is")
    print(" * a hung GPU with no diagnostic when it is wrong.")
    print(" *")
    print(" * The four colour channels are 32-bit float IMMEDIATES inside the mov")
    print(" * instructions, so a caller patches them in place instead of recompiling.")
    print(" * Their offsets were found by SEARCHING for the known constants, not by a")
    print(" * fixed table - an offset table would be right for this Mesa and quietly")
    print(" * wrong for the next one.")
    print(" *")
    print(f" * {len(by)} bytes, {len(by)//16} instructions:")
    for line in blk.splitlines():
        m = re.match(r'^(?:[0-9a-f]{2} ){16}(\S.*)$', line.strip())
        if m:
            # Mesa's disassembly carries its own /* 0.376F */ comments, and
            # pasting those inside this header would CLOSE it at the first */ -
            # turning the rest of the line into code and the file into a syntax
            # error. Caught by compiling the generated .inc, not by reading it.
            print(" *   " + m.group(1).replace("/*", "(").replace("*/", ")"))
    print(" */")
    print(f"#define GPU_SHADER_BYTES {len(by)}u")
    for name, o in zip(("R", "G", "B", "A"), off):
        print(f"#define GPU_SHADER_OFF_{name} {o}u")
    print("static const unsigned char gpu_shader_simd8[GPU_SHADER_BYTES] = {")
    for i in range(0, len(by), 8):
        print("    " + " ".join(f"0x{x:02X}," for x in by[i:i+8]))
    print("};")

main()
