/* Generated by kernel/tools/generators/gen-user-syscalls.py. */
/* Source SHA-256: b7ad9c0a9567aec99e4c9d0a4203c5eb40312e9a6cf1fef267249729a4f701f5 */
#ifndef ZLOS_USER_SYSCALLS_GENERATED_H
#define ZLOS_USER_SYSCALLS_GENERATED_H

#define ZLOS_U64_SYSCALL_ABI_VERSION 1ULL
#define ZLOS_U64_SYSCALL_FIRST 1ULL
#define ZLOS_U64_SYSCALL_LAST 24ULL
#define U64_SYS_WRITE 1ULL
#define U64_SYS_GETPID 2ULL
#define U64_SYS_EXIT 3ULL
#define U64_SYS_COPY 4ULL
#define U64_SYS_TIME 5ULL
#define U64_SYS_YIELD 6ULL
#define U64_SYS_OPEN 7ULL
#define U64_SYS_READ 8ULL
#define U64_SYS_WRITEF 9ULL
#define U64_SYS_CLOSE 10ULL
#define U64_SYS_INFO 11ULL
#define U64_SYS_REMOVE 12ULL
#define U64_SYS_RENAME 13ULL
#define U64_SYS_SYNC 14ULL
#define U64_SYS_SEND 15ULL
#define U64_SYS_RECV 16ULL
#define U64_SYS_FROM 17ULL
#define U64_SYS_WIN_OPEN 18ULL
#define U64_SYS_WIN_PRESENT 19ULL
#define U64_SYS_WIN_POLL 20ULL
#define U64_SYS_WIN_CLOSE 21ULL
#define U64_SYS_ANON_RESERVE 22ULL
#define U64_SYS_ANON_COMMIT 23ULL
#define U64_SYS_ANON_RELEASE 24ULL

static int zlos_u64_syscall_known(unsigned long long number)
{
    switch (number) {
    case U64_SYS_WRITE:
    case U64_SYS_GETPID:
    case U64_SYS_EXIT:
    case U64_SYS_COPY:
    case U64_SYS_TIME:
    case U64_SYS_YIELD:
    case U64_SYS_OPEN:
    case U64_SYS_READ:
    case U64_SYS_WRITEF:
    case U64_SYS_CLOSE:
    case U64_SYS_INFO:
    case U64_SYS_REMOVE:
    case U64_SYS_RENAME:
    case U64_SYS_SYNC:
    case U64_SYS_SEND:
    case U64_SYS_RECV:
    case U64_SYS_FROM:
    case U64_SYS_WIN_OPEN:
    case U64_SYS_WIN_PRESENT:
    case U64_SYS_WIN_POLL:
    case U64_SYS_WIN_CLOSE:
    case U64_SYS_ANON_RESERVE:
    case U64_SYS_ANON_COMMIT:
    case U64_SYS_ANON_RELEASE:
        return 1;
    default:
        return 0;
    }
}

#endif
