/* font_prop.h - GENERATED by gen_prop_font.py. Do not edit.
 * The proportional atlas cell sizes, so fb.c's extern declarations
 * cannot drift from the data. A mismatch here is not a compile
 * error, it is a silently misindexed array. */
#ifndef FONT_PROP_H
#define FONT_PROP_H
#define PROP8_W  16
#define PROP16_W 30
#endif
