/* font_prop.h - GENERATED by gen_prop_font.py. Do not edit.
 * The proportional atlas cell WIDTHS, so fb.c's extern declarations
 * cannot drift from the data. A mismatch here is not a compile
 * error, it is a silently misindexed array. */
#ifndef FONT_PROP_H
#define FONT_PROP_H
#define PROP16_W 16
#define PROP16B_W 18
#define PROP24_W 22
#define PROP24B_W 24
#define PROP32_W 30
#define PROP32B_W 33
#endif
