#!/usr/bin/env python3
# gen_hd_font.py - render a REAL high-resolution font into our coverage atlases.
#
# Our hand-drawn 8x16 font, even anti-aliased, is limited by its own coarse
# master: upscaling an 8x16 grid cannot invent detail. This renders a real
# TrueType font (DejaVu Sans Mono) with FreeType's grayscale hinting straight
# into the exact same coverage arrays the kernel already reads, so it is a
# DROP-IN replacement for font_aa.c - no renderer changes, just crisper data.
#
#   font8x16_aa[95][16][8]   - body text, the whole console
#   font16x32_aa[95][32][16] - titles and headers
#
# To revert to our own hand-drawn font, run gen_aa_font.py instead.

import os, sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "font_aa.c")
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FIRST, LAST = 32, 126

def best_size(cell_w, cell_h):
    """largest font size whose advance fits cell_w and line fits cell_h"""
    best = 6
    for s in range(6, cell_h * 3):
        f = ImageFont.truetype(FONT, s)
        adv = f.getlength("M")
        asc, desc = f.getmetrics()
        if adv <= cell_w and (asc + desc) <= cell_h + 2:
            best = s
    return best

def render_cell(font, ch, W, H, baseline):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    adv = font.getlength(ch)
    x = (W - adv) / 2.0
    # 'ls' = anchor at the left end of the baseline: proper terminal alignment
    d.text((x, baseline), ch, font=font, fill=255, anchor="ls")
    return [[img.getpixel((x, y)) for x in range(W)] for y in range(H)]

def build(W, H):
    size = best_size(W, H)
    font = ImageFont.truetype(FONT, size)
    asc, desc = font.getmetrics()
    baseline = (H + asc - desc) // 2          # centre the line box vertically
    glyphs = []
    for code in range(FIRST, LAST + 1):
        glyphs.append(render_cell(font, chr(code), W, H, baseline))
    return glyphs, size

def emit(f, name, W, H, glyphs):
    f.write(f"const unsigned char {name}[95][{H}][{W}] = {{\n")
    for i, g in enumerate(glyphs):
        f.write("  { /* %d */\n" % (FIRST + i))
        for row in g:
            f.write("    {" + ",".join("%3d" % v for v in row) + "},\n")
        f.write("  },\n")
    f.write("};\n")

def main():
    small, s_sz = build(8, 16)
    big,   b_sz = build(16, 32)
    with open(OUT, "w") as f:
        f.write("/* font_aa.c - GENERATED by gen_hd_font.py. Do not edit by hand.\n")
        f.write(" * Real DejaVu Sans Mono, rendered with FreeType grayscale AA into the\n")
        f.write(" * kernel's coverage atlases. A drop-in replacement for the hand-font\n")
        f.write(f" * version - body at {s_sz}px, titles at {b_sz}px. fb.c blends fg over bg\n")
        f.write(" * by these coverage values. Run gen_aa_font.py to revert to our font. */\n")
        emit(f, "font8x16_aa", 8, 16, small)
        f.write("\n")
        emit(f, "font16x32_aa", 16, 32, big)
    print(f"wrote {OUT}: DejaVu Sans Mono, body {s_sz}px + titles {b_sz}px")

if __name__ == "__main__":
    main()
