#!/usr/bin/env python3
# gen_aa_font.py - turn our hand-drawn 1-bit font8x16 into a COVERAGE font.
#
# The 8x16 bitmap has hard on/off pixels, so text staircases on diagonals and
# reads as 1990. This does NOT change the letter shapes - it takes the exact
# same glyphs and computes an alpha (coverage 0..255) per pixel by:
#   1. reading font8x16.c back into 8x16 1-bit grids,
#   2. edge-smoothing them up to 4x resolution with scale2x (EPX) applied
#      twice - the classic pixel-art smoother that infers clean diagonals,
#   3. box-downsampling the 32x64 result back to 8x16, averaging each 4x4
#      block into a coverage value.
# The runtime then blends fg over the real background by that coverage, so the
# edges go grey instead of jagged. Same font, anti-aliased.
#
# Output: font_aa.c  ->  const unsigned char font8x16_aa[95][16][8];

import re, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "font8x16.c")
OUT  = os.path.join(HERE, "font_aa.c")
W, H = 8, 16

def load_glyphs():
    txt = open(SRC).read()
    # each glyph is a { ... 16 hex bytes ... } row
    rows = re.findall(r"\{\s*((?:0x[0-9A-Fa-f]+\s*,\s*){15}0x[0-9A-Fa-f]+)\s*\}", txt)
    glyphs = []
    for r in rows:
        bytes_ = [int(b, 16) for b in re.findall(r"0x[0-9A-Fa-f]+", r)]
        # 16 rows, bit 7 = leftmost column
        grid = [[(bytes_[y] >> (7 - x)) & 1 for x in range(W)] for y in range(H)]
        glyphs.append(grid)
    return glyphs

def get(g, x, y, w, h):
    if x < 0 or y < 0 or x >= w or y >= h:
        return 0
    return g[y][x]

def scale2x(g, w, h):
    """EPX / scale2x: 1 pixel -> 2x2, inferring smooth edges."""
    out = [[0] * (w * 2) for _ in range(h * 2)]
    for y in range(h):
        for x in range(w):
            P = g[y][x]
            A = get(g, x, y - 1, w, h)   # up
            B = get(g, x + 1, y, w, h)   # right
            C = get(g, x - 1, y, w, h)   # left
            D = get(g, x, y + 1, w, h)   # down
            e0 = e1 = e2 = e3 = P
            if C == A and C != D and A != B: e0 = A
            if A == B and A != C and B != D: e1 = B
            if D == C and D != B and C != A: e2 = C
            if B == D and B != A and D != C: e3 = D
            out[y * 2][x * 2]         = e0
            out[y * 2][x * 2 + 1]     = e1
            out[y * 2 + 1][x * 2]     = e2
            out[y * 2 + 1][x * 2 + 1] = e3
    return out, w * 2, h * 2

def downsample(up, uw, uh, tw, th):
    """box-downsample an uw x uh 0/1 image to tw x th coverage 0..255"""
    sx, sy = uw // tw, uh // th
    cov = [[0] * tw for _ in range(th)]
    for cy in range(th):
        for cx in range(tw):
            s = 0
            for dy in range(sy):
                for dx in range(sx):
                    s += up[cy * sy + dy][cx * sx + dx]
            cov[cy][cx] = (s * 255) // (sx * sy)
    return cov

def coverage(g):
    # 8x16 -> 32x64 (scale2x twice), then downsample two ways:
    #   /4 -> 8x16   (same-size AA, the whole console)
    #   /2 -> 16x32  (double-size AA, for titles + headers)
    up, w, h = scale2x(g, W, H)
    up, w, h = scale2x(up, w, h)          # now 32x64
    return downsample(up, w, h, W, H), downsample(up, w, h, W * 2, H * 2)

def main():
    glyphs = load_glyphs()
    if len(glyphs) != 95:
        print(f"expected 95 glyphs, parsed {len(glyphs)}", file=sys.stderr)
        sys.exit(1)
    small, big = [], []
    for g in glyphs:
        s, b = coverage(g)
        small.append(s)
        big.append(b)
    with open(OUT, "w") as f:
        f.write("/* font_aa.c - GENERATED by gen_aa_font.py. Do not edit by hand.\n")
        f.write(" * Coverage (alpha 0..255) fonts derived from our own font8x16, by\n")
        f.write(" * scale2x-smoothing each hand-drawn glyph and downsampling. Same shapes,\n")
        f.write(" * anti-aliased edges. fb.c blends foreground over background by these.\n")
        f.write(" *   font8x16_aa  - same-size AA, used by the whole console\n")
        f.write(" *   font16x32_aa - double-size AA, used for titles and headers */\n")
        f.write("const unsigned char font8x16_aa[95][16][8] = {\n")
        for i, cov in enumerate(small):
            f.write("  { /* %d */\n" % (32 + i))
            for row in cov:
                f.write("    {" + ",".join("%3d" % v for v in row) + "},\n")
            f.write("  },\n")
        f.write("};\n\n")
        f.write("const unsigned char font16x32_aa[95][32][16] = {\n")
        for i, cov in enumerate(big):
            f.write("  { /* %d */\n" % (32 + i))
            for row in cov:
                f.write("    {" + ",".join("%3d" % v for v in row) + "},\n")
            f.write("  },\n")
        f.write("};\n")
    print(f"wrote {OUT}: 95 glyphs, 8x16 + 16x32 coverage fonts")

if __name__ == "__main__":
    main()
