#!/usr/bin/env python3
# gen_subfont.py - SUBPIXEL coverage fonts (what Windows calls ClearType).
#
# An LCD pixel is not one dot. It is three vertical stripes - red, green, blue,
# left to right - and each can be lit independently. Ordinary antialiasing
# ignores that and computes ONE coverage value per pixel. Subpixel rendering
# computes THREE, one per stripe, which triples the effective horizontal
# resolution of text at exactly the same cost per pixel: the same number of
# pixels get written, they just carry three alphas instead of one.
#
# The research was blunt that this is "the single biggest visual difference
# between OS text and hobby-OS text", and zlOS is already set up for it -
# blend_rgb in fb.c blends each channel separately, it was simply being handed
# the same coverage three times.
#
# Method (the standard one):
#   1. rasterise each glyph at 3x horizontal resolution, so every subpixel
#      stripe gets its own coverage sample
#   2. run a 5-tap FIR filter (1,2,3,2,1)/9 along that 3x row
#
# The filter is the important half. Without it, a stem landing on the red
# stripe simply makes the text look red - "colour fringing". The filter spreads
# each subpixel's energy into its neighbours, which is what turns a colour
# artefact back into apparent resolution.
#
# Output: font_sub.c
#     font8x16_sub[95][16][8][3]    body text
#     font16x32_sub[95][32][16][3]  titles

import os, sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "font_sub.c")
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FIRST, LAST = 32, 126

# FreeType's default LCD filter, which is what ClearType-class rendering
# actually ships. It is far more centre-weighted than the naive (1,2,3,2,1)/9:
# that one spreads a stem's energy over +/-0.67 of a pixel and the result reads
# as BLUR rather than as extra resolution. This one keeps ~85% of the weight in
# the middle three taps, which suppresses colour fringing while staying sharp.
FIR = (0x08, 0x4D, 0x56, 0x4D, 0x08)
FIR_SUM = 256


def best_size(cell_w, cell_h):
    """largest size whose advance fits the cell - same rule as the grey font"""
    best = 6
    for s in range(6, cell_h * 3):
        f = ImageFont.truetype(FONT, s)
        asc, desc = f.getmetrics()
        if f.getlength("M") <= cell_w and (asc + desc) <= cell_h + 2:
            best = s
    return best


def render_3x(font, ch, W, H, baseline):
    """rasterise one glyph at 3x horizontal resolution"""
    img = Image.new("L", (W * 3, H), 0)
    d = ImageDraw.Draw(img)
    # the whole glyph is stretched 3x across, so x positions triple too
    adv = font.getlength(ch)
    x = (W - adv) / 2.0
    big = ImageFont.truetype(FONT, font.size)
    # draw into a 3x-wide canvas by scaling a high-res render down vertically
    hi = Image.new("L", (W * 3, H * 3), 0)
    dh = ImageDraw.Draw(hi)
    fh = ImageFont.truetype(FONT, font.size * 3)
    dh.text((x * 3, baseline * 3), ch, font=fh, fill=255, anchor="ls")
    img = hi.resize((W * 3, H), Image.BOX)   # vertical box filter only
    return img.load(), img.size


def subpixel_cell(px, W, H):
    """3x coverage -> three filtered alphas per output pixel"""
    out = [[[0, 0, 0] for _ in range(W)] for _ in range(H)]
    span = W * 3
    for y in range(H):
        for x in range(W):
            for c in range(3):                 # 0=R, 1=G, 2=B stripe
                centre = x * 3 + c
                acc = 0
                for k, w in enumerate(FIR):
                    s = centre + k - 2         # taps at -2..+2
                    if 0 <= s < span:
                        acc += px[s, y] * w
                out[y][x][c] = min(255, acc // FIR_SUM)
    return out


def build(W, H):
    size = best_size(W, H)
    font = ImageFont.truetype(FONT, size)
    asc, desc = font.getmetrics()
    baseline = (H + asc - desc) // 2
    glyphs = []
    for code in range(FIRST, LAST + 1):
        px, _ = render_3x(font, chr(code), W, H, baseline)
        glyphs.append(subpixel_cell(px, W, H))
    return glyphs, size


def emit(f, name, W, H, glyphs):
    f.write(f"const unsigned char {name}[95][{H}][{W}][3] = {{\n")
    for i, g in enumerate(glyphs):
        f.write("  { /* %d */\n" % (FIRST + i))
        for row in g:
            cells = ",".join("{%3d,%3d,%3d}" % (p[0], p[1], p[2]) for p in row)
            f.write("    {" + cells + "},\n")
        f.write("  },\n")
    f.write("};\n")


def main():
    small, s_sz = build(8, 16)
    big,   b_sz = build(16, 32)
    with open(OUT, "w") as f:
        f.write("/* font_sub.c - GENERATED by gen_subfont.py. Do not edit.\n")
        f.write(" * Subpixel (LCD stripe) coverage: three alphas per pixel, one per\n")
        f.write(" * colour stripe, filtered with the standard 5-tap (1,2,3,2,1)/9 FIR\n")
        f.write(f" * to suppress colour fringing. Body {s_sz}px, titles {b_sz}px. */\n")
        emit(f, "font8x16_sub", 8, 16, small)
        f.write("\n")
        emit(f, "font16x32_sub", 16, 32, big)
    print(f"wrote {OUT}: subpixel fonts, body {s_sz}px + titles {b_sz}px")


if __name__ == "__main__":
    main()
