#!/usr/bin/env python3
# gen_prop_font.py - the PROPORTIONAL companion to gen_hd_font.py.
#
# desktop-look.md's item 4, and it calls it "the one that stops the desktop
# reading as a terminal":
#
#     fb_text_aa advances by exactly cell_w per character, so EVERY string on
#     screen is monospace-positioned, including window titles and dock labels.
#     Uniform advance is the single strongest visual signal of "this is a
#     terminal", and it is applied to things that are not terminals.
#
# That document proposes emitting per-glyph advance widths from the existing
# atlas. THAT ALONE DOES NOTHING, and it is worth saying why before anyone
# tries it: the atlas font is DejaVu Sans **Mono**. Every advance FreeType
# reports for it is the same number, so a per-glyph advance table would be 95
# copies of one value and the screen would not change by a pixel.
#
# Real proportional text needs a proportional FACE. This uses DejaVu Sans - the
# proportional cut of the same superfamily, same designer, same shapes, drawn
# for exactly this purpose. That is a reading of "no new fonts" that keeps the
# rule's intent (do not introduce a second visual system) while getting the
# thing the rule was never about.
#
#   font8x16_prop[95][16][10]   +  prop8_adv[95]
#   font16x32_prop[95][32][20]  +  prop16_adv[95]
#
# THE CELL IS WIDER THAN THE ADVANCE, on purpose. A proportional glyph can be
# wider than the advance it hands on - 'm' and 'W' notably - and can carry a
# negative left bearing. The cell is sized to the widest INK box so nothing is
# ever cropped, while the pen still moves by the real advance. Cropping a glyph
# to its advance is the classic way proportional text ends up with clipped
# round letters.
#
# The console keeps its grid and keeps the mono atlas. Only titles and labels
# change, which is exactly what desktop-look.md asks for.

import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "font_prop.inc")
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FIRST, LAST = 32, 126
CHARS = [chr(c) for c in range(FIRST, LAST + 1)]


def best_size(cell_h):
    """largest size whose line box fits the cell height"""
    best = 6
    for s in range(6, cell_h * 3):
        f = ImageFont.truetype(FONT, s)
        asc, desc = f.getmetrics()
        if asc + desc <= cell_h + 2:
            best = s
    return best


def measure(font):
    """(cell width, advances, ink widths). The cell must hold the widest INK
    box, including any part that sits left of the pen (a negative bearing).

    The per-glyph INK width is what the renderer actually has to blit. Drawing
    the full cell for every glyph is correct - coverage is zero outside the ink
    - but at title size the cell is 30px and a comma's ink is 4, so it is up to
    7x the pixels touched for nothing. Measured at 35% over the mono path
    before this was added."""
    wide, advs, boxes = 0, [], []
    for ch in CHARS:
        adv = font.getlength(ch)
        box = font.getbbox(ch)              # (x0, y0, x1, y1), ink relative to pen
        need = max(box[2], adv)             # ink may overhang the advance
        left = min(box[0], 0)               # ...and may start left of it
        wide = max(wide, int(need - left) + 1)
        advs.append(int(round(adv)))
        boxes.append(int(need - left) + 1)
    inks = [min(b, wide) for b in boxes]
    return wide, advs, inks


def build(cell_h):
    size = best_size(cell_h)
    font = ImageFont.truetype(FONT, size)
    cell_w, advs, inks = measure(font)
    asc, desc = font.getmetrics()
    baseline = (cell_h + asc - desc) // 2

    glyphs = []
    for ch in CHARS:
        img = Image.new("L", (cell_w, cell_h), 0)
        d = ImageDraw.Draw(img)
        # 'ls' anchors at the left end of the baseline, i.e. AT THE PEN - which
        # is what makes the advance below actually mean something.
        d.text((0, baseline), ch, font=font, fill=255, anchor="ls")
        glyphs.append([[img.getpixel((x, y)) for x in range(cell_w)]
                       for y in range(cell_h)])
    return glyphs, advs, inks, cell_w, size


def emit(f, name, cw, ch, glyphs):
    f.write(f"const unsigned char {name}[95][{ch}][{cw}] = {{\n")
    for i, g in enumerate(glyphs):
        f.write("  { /* %d %r */\n" % (FIRST + i, CHARS[i]))
        for row in g:
            f.write("    {" + ",".join("%3d" % v for v in row) + "},\n")
        f.write("  },\n")
    f.write("};\n")


def emit_adv(f, name, advs):
    f.write(f"const unsigned char {name}[95] = {{\n  ")
    f.write(",".join("%3d" % a for a in advs))
    f.write("\n};\n")


def main():
    small, s_adv, s_ink, s_cw, s_sz = build(16)
    big,   b_adv, b_ink, b_cw, b_sz = build(32)

    with open(OUT, "w") as f:
        f.write("/* font_prop.inc - GENERATED by gen_prop_font.py. Do not edit by hand.\n")
        f.write(" *\n")
        f.write(" * INCLUDED BY fb.c, not compiled on its own. That is deliberate: fb.c is\n")
        f.write(" * in every build - 32-bit, 64-bit, the UEFI application and the raw disk\n")
        f.write(" * image - and each of those has its own source list. A new .c file would\n")
        f.write(" * have had to be added to four of them, one of which another session is\n")
        f.write(" * mid-flight in. Riding along with fb.c needs no build change at all.\n")
        f.write(" *\n")
        f.write(" * DejaVu SANS - proportional, the companion to the Mono in font_aa.c.\n")
        f.write(" * UI labels and window titles draw from this; the CONSOLE keeps its\n")
        f.write(" * grid and keeps the mono atlas. Uniform advance is the strongest\n")
        f.write(' * "this is a terminal" signal there is, and it was being applied to\n')
        f.write(" * things that are not terminals (desktop-look.md, item 4).\n")
        f.write(" *\n")
        f.write(" * The CELL IS WIDER THAN THE ADVANCE on purpose: a proportional glyph\n")
        f.write(" * can overhang the advance it hands on, and can start left of the pen.\n")
        f.write(" * The cell holds the widest ink box so nothing is cropped; the pen\n")
        f.write(" * moves by the real advance from the tables below.\n")
        f.write(f" *\n * body  {s_sz}px, cell {s_cw}x16, advances {min(s_adv)}..{max(s_adv)}\n")
        f.write(f" * title {b_sz}px, cell {b_cw}x32, advances {min(b_adv)}..{max(b_adv)}\n")
        f.write(" */\n")
        f.write('#include "font_prop.h"\n\n')
        emit(f, "font8x16_prop", s_cw, 16, small)
        f.write("\n")
        emit_adv(f, "prop8_adv", s_adv)
        f.write("\n")
        emit_adv(f, "prop8_ink", s_ink)
        f.write("\n")
        emit(f, "font16x32_prop", b_cw, 32, big)
        f.write("\n")
        emit_adv(f, "prop16_adv", b_adv)
        f.write("\n")
        emit_adv(f, "prop16_ink", b_ink)

    # A header, so fb.c's array declarations cannot drift out of step with the
    # generated cell widths. Getting those wrong is not a compile error - it is
    # a silently misindexed atlas, which draws garbage that looks like a font
    # bug rather than a build one.
    hdr = os.path.join(HERE, "font_prop.h")
    with open(hdr, "w") as f:
        f.write("/* font_prop.h - GENERATED by gen_prop_font.py. Do not edit.\n")
        f.write(" * The proportional atlas cell sizes, so fb.c's extern declarations\n")
        f.write(" * cannot drift from the data. A mismatch here is not a compile\n")
        f.write(" * error, it is a silently misindexed array. */\n")
        f.write("#ifndef FONT_PROP_H\n#define FONT_PROP_H\n")
        f.write(f"#define PROP8_W  {s_cw}\n#define PROP16_W {b_cw}\n")
        f.write("#endif\n")

    print(f"wrote {OUT} and {hdr}")
    print(f"  body  {s_sz}px  cell {s_cw}x16   advances {min(s_adv)}..{max(s_adv)}")
    print(f"  title {b_sz}px  cell {b_cw}x32   advances {min(b_adv)}..{max(b_adv)}")
    print(f"  bytes: {95*16*s_cw + 95*32*b_cw + 190}")
    # the point of the whole exercise, as a number
    uniq_s, uniq_b = len(set(s_adv)), len(set(b_adv))
    print(f"  DISTINCT advances: {uniq_s} at body size, {uniq_b} at title size")
    print("  (DejaVu Sans MONO would give 1 and 1 - which is why emitting")
    print("   advances from the existing atlas would have changed nothing)")


if __name__ == "__main__":
    main()
