#!/usr/bin/env bash
# todo.sh - regenerate TODO.md from what the tools actually measure.
#
# A hand-maintained TODO drifts: items get fixed and stay listed, or rot appears
# and never gets written down. This one is derived, so it cannot lie about the
# things it covers. Everything in it comes from a command that ran just now.
#
#   tools/todo.sh            write TODO.md
#   tools/todo.sh --stdout   print instead, change nothing
#
# Hand-written items go in the HOLD block at the bottom of TODO.md, between the
# two markers. That block is preserved across regenerations - everything above
# it is derived and will be overwritten.

set -uo pipefail
cd "$(dirname "$0")/.." || exit

OUT=TODO.md
BEGIN_HOLD="<!-- BEGIN HAND-WRITTEN -->"
END_HOLD="<!-- END HAND-WRITTEN -->"

open_tension_headings() {
    grep -iE '^#{2,3} T-[0-9]+ .*OPEN\.?$' "$1" 2>/dev/null || true
}

if [ "${1:-}" = "--selftest-tensions" ]; then
    fixture=$(mktemp)
    trap 'rm -f "$fixture"' EXIT
    printf '%s\n' \
        '## T-1 — old problem. CLOSED.' \
        '## T-2 — current problem. OPEN.' \
        '### T-3 | 2026-08-25 | open' > "$fixture"
    found=$(open_tension_headings "$fixture")
    [ "$(printf '%s\n' "$found" | grep -c '^')" -eq 2 ] || {
        echo "todo tension selftest: FAIL"
        exit 1
    }
    echo "todo tension selftest: caught both supported OPEN heading formats"
    exit 0
fi

# Preserve anything the human wrote between the markers.
hold=""
if [ -f "$OUT" ] && grep -qF "$BEGIN_HOLD" "$OUT"; then
    hold=$(sed -n "/$BEGIN_HOLD/,/$END_HOLD/p" "$OUT")
fi

gen() {
cat <<HEADER
# TODO

Generated by \`tools/todo.sh\` — **do not edit above the hand-written block.**
Every item below was measured by a command, not remembered. Regenerate with:

\`\`\`bash
tools/todo.sh
\`\`\`

HEADER

# ---- 1. the EFI warning-contract backlog ----------------------------------
if command -v clang >/dev/null 2>&1; then
    n=$(tools/hazard-scan.sh --count 2>/dev/null || echo "?")
    if [ "$n" != "0" ] && [ "$n" != "?" ]; then
        echo "## EFI warning-contract failures — $n sites"
        echo
        echo "The live warning-strict EFI flags reject the dedicated pointer-truncation"
        echo "probe, but compiling the shipped EFI translation units reported errors."
        echo
        echo "- [ ] inspect and repair the reported translation units:"
        echo
        tools/hazard-scan.sh 2>/dev/null | sed -n '/== 2\./,/^  \(WARN\|ok\|HAZARD\)/p' \
            | grep -E '^     ' | while read -r f c; do
                # hazard-scan compiles from kernel/, so it reports paths relative
                # to there; make them repo-relative so the links are clickable.
                case "$f" in ../*) f="${f#../}" ;; *) f="kernel/$f" ;; esac
                echo "  - [ ] \`$f\` — $c site(s)"
            done
        echo "- [ ] then run the static hazard scan; leave hardware/QEMU proof for its explicit gate"
        echo
    fi
fi

# ---- 2. engine divergences --------------------------------------------------
if [ -f tools/engine-parity-expected.txt ]; then
    pins=$(grep -vE '^\s*#|^\s*$' tools/engine-parity-expected.txt | wc -l)
    if [ "$pins" -gt 0 ]; then
        echo "## Engine divergence — $pins pinned"
        echo
        echo "\`./interp\` is ground truth. These engines disagree with it today:"
        echo
        grep -vE '^\s*#|^\s*$' tools/engine-parity-expected.txt | while read -r case eng; do
            echo "- [ ] \`$case\` — \`$eng\` differs"
        done
        echo
        echo "Both unboxed backends sit on the far side of the scoping decision in"
        echo "\`docs/design/design_scoping_decision.md\`. Delete these pins when it lands;"
        echo "\`tools/engine-parity.sh\` fails if a pin stops being true."
        echo
    fi
fi

# ---- 3. documented but untracked -------------------------------------------
echo "## Documented but not in git"
echo
missing=0
while IFS= read -r f; do
    [ -z "$f" ] && continue
    git ls-files --error-unmatch "$f" >/dev/null 2>&1 || { echo "- [ ] \`$f\`"; missing=$((missing+1)); }
done <<LIST
$(git ls-files '*.md' | xargs grep -ohE '\b(kernel|docs|tools|examples|tests)/[A-Za-z0-9_./-]+\.(c|h|zl|sh)\b' 2>/dev/null | sort -u | while read -r r; do [ -e "$r" ] && echo "$r"; done)
LIST
[ "$missing" -eq 0 ] && echo "_none — every file the docs describe is tracked._"
echo

# ---- 4. doc rot backlog -----------------------------------------------------
if [ -f tools/doc-check-ignore.txt ]; then
    rot=$(grep -vE '^\s*#|^\s*$' tools/doc-check-ignore.txt | wc -l)
    if [ "$rot" -gt 0 ]; then
        echo "## Stale doc references — $rot baselined"
        echo
        echo "Delete a line from \`tools/doc-check-ignore.txt\` as you fix it. New rot fails CI."
        echo
        grep -vE '^\s*#|^\s*$' tools/doc-check-ignore.txt | while read -r l; do
            echo "- [ ] $l"
        done
        echo
    fi
fi

# ---- 5. open tensions -------------------------------------------------------
if [ -f .ultra/TENSIONS.md ]; then
    echo "## Open tensions (.ultra/TENSIONS.md)"
    echo
    headings=$(open_tension_headings .ultra/TENSIONS.md)
    open=$(printf '%s' "$headings" | grep -c '^' || true)
    if [ "$open" -gt 0 ]; then
        printf '%s\n' "$headings" | while read -r l; do
            id=$(echo "$l" | grep -oE 'T-[0-9]+')
            body=$(echo "$l" | sed -E 's/^#{2,3} T-[0-9]+ [—|-] *//; s/ *OPEN\.?$//' | cut -c1-110)
            echo "- [ ] **$id** — $body"
        done
    else
        echo "_none open._"
    fi
    echo
fi

# ---- 6. open PRs ------------------------------------------------------------
if command -v gh >/dev/null 2>&1; then
    prs=$(timeout 20 gh pr list --limit 20 --json number,title,headRefName \
          --jq '.[] | "- [ ] #\(.number) \(.title)  `\(.headRefName)`"' 2>/dev/null || true)
    if [ -n "$prs" ]; then
        echo "## Open pull requests"; echo; echo "$prs"; echo
    fi
fi

echo "---"
echo
if [ -n "$hold" ]; then
    echo "$hold"
else
    echo "$BEGIN_HOLD"
    echo
    echo "## Hand-written"
    echo
    echo "_Items here survive regeneration. Everything above does not._"
    echo
    echo "$END_HOLD"
fi
}

if [ "${1:-}" = "--stdout" ]; then gen; exit 0; fi
gen > "$OUT"
echo "wrote $OUT ($(grep -c '^- \[ \]' "$OUT") open items)"
